package com.stepdefination;

import com.pages.Searchby_hintpage;

import cucumber.api.java.en.Given;
import cucumber.api.java.en.Then;
import cucumber.api.java.en.When;

public class searchbyhint_steps {
	//* object creation for page*//
	Searchby_hintpage jph= new Searchby_hintpage();

	
	//* steps generated by testcase.feature *//
	@Given("^:Open the url in Browser$")
	public void open_the_url_in_Browser()  {
		jph.url("chrome");
	    
	}

	
	
	@When("^:Enter the Item name with hint$")
	public void enter_the_Item_name_with_hint()  {
		//* calling the method using object *//
		jph.JpetSearch();
	}
	    
	@Then("^:click on Searchbutton$")
	public void click_on_Searchbutton() {
		jph.click();
	    
	}
	@Then("^:Close the jpetsite$")
	public void close_the_jpetsite() {
		jph.close();
	   
	}
}





